"""Progression API: profiles, settings, skill tree.

The profile is server-authoritative: XP, badges, nodes, and career state
mutate only through progression events generated by graded gameplay (over
the WebSocket) or drill verification. The only client-writable surface is
the settings patch and client-verified drill results.
"""

from typing import Any, Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from api.game_session import COUNTING_SYSTEMS, RULE_PRESETS, VISIBILITY_MODES
from api.progression_store import (
    create_profile,
    get_or_create_profile,
    load_profile,
    progress,
    save_profile,
)
from core.progression import BADGES, SKILL_TREE

router = APIRouter()

# Drills verified in the browser (the server hands the answer out with the
# drill); everything else must arrive via server-graded paths.
CLIENT_REPORTABLE_DRILLS = {"strategy", "deviation"}


def _profile_response(profile) -> dict[str, Any]:
    data = profile.model_dump(mode="json")
    data["title"] = profile.title
    return data


class SettingsPatch(BaseModel):
    counting_system: str | None = None
    visibility: str | None = None
    sound: bool | None = None
    rules_preset: str | None = None


class DrillEventRequest(BaseModel):
    drill_key: Literal["strategy", "deviation"]
    correct: bool
    true_count: float | None = None
    fab4: bool = Field(default=False, description="Was this a Fab 4 surrender index?")


@router.post("/profile")
async def create_player_profile() -> dict[str, Any]:
    """Create a fresh profile; the client stores the id in localStorage."""
    profile = await create_profile()
    return _profile_response(profile)


@router.get("/profile/{profile_id}")
async def get_player_profile(profile_id: str) -> dict[str, Any]:
    profile = await get_or_create_profile(profile_id)
    return _profile_response(profile)


@router.patch("/profile/{profile_id}/settings")
async def patch_settings(profile_id: str, patch: SettingsPatch) -> dict[str, Any]:
    profile = await load_profile(profile_id)
    if profile is None:
        raise HTTPException(status_code=404, detail="Unknown profile")

    if patch.counting_system is not None:
        if patch.counting_system not in COUNTING_SYSTEMS:
            raise HTTPException(status_code=422, detail="Unknown counting system")
        profile.settings.counting_system = patch.counting_system
    if patch.visibility is not None:
        if patch.visibility not in VISIBILITY_MODES:
            raise HTTPException(status_code=422, detail="Unknown visibility mode")
        profile.settings.visibility = patch.visibility
    if patch.rules_preset is not None:
        if patch.rules_preset not in RULE_PRESETS:
            raise HTTPException(status_code=422, detail="Unknown rules preset")
        profile.settings.rules_preset = patch.rules_preset
    if patch.sound is not None:
        profile.settings.sound = patch.sound

    await save_profile(profile)
    return _profile_response(profile)


@router.post("/profile/{profile_id}/drill-event")
async def record_client_drill(profile_id: str, request: DrillEventRequest) -> dict[str, Any]:
    """Record a client-verified drill attempt (strategy/deviation only)."""
    if request.drill_key not in CLIENT_REPORTABLE_DRILLS:
        raise HTTPException(status_code=422, detail="Drill is server-verified")
    delta = await progress(
        profile_id,
        "drill",
        {
            "drill_key": request.drill_key,
            "correct": request.correct,
        },
    )
    if delta is None:
        raise HTTPException(status_code=404, detail="Unknown profile")
    if request.fab4 and request.correct:
        extra = await progress(
            profile_id, "decision",
            {"correct": True, "is_deviation": True, "visibility": "hidden", "fab4": True},
        )
        if extra:
            delta.xp_gained += extra.xp_gained
            delta.xp_total = extra.xp_total
            delta.badges_awarded += extra.badges_awarded
            delta.node_changes.update(extra.node_changes)
    return delta.model_dump(mode="json")


@router.get("/skill-tree/{profile_id}")
async def get_skill_tree(profile_id: str) -> dict[str, Any]:
    profile = await get_or_create_profile(profile_id)
    nodes = []
    for node in SKILL_TREE.values():
        state = profile.nodes.get(node.id)
        nodes.append(
            {
                "id": node.id,
                "stage": node.stage,
                "name": node.name,
                "description": node.description,
                "drill_key": node.drill_key,
                "gate": node.mastery.describe(),
                "prerequisites": list(node.prerequisites),
                "unlocks": list(node.unlocks),
                "status": state.status if state else "locked",
                "progress": state.progress if state else 0.0,
                "attempts": state.attempts if state else 0,
            }
        )
    return {"nodes": nodes}


@router.get("/daily")
async def daily_meta(profile_id: str | None = None) -> dict[str, Any]:
    """Today's challenge metadata plus this profile's attempt, if any."""
    from datetime import date

    from core.progression.daily import challenge_for_date

    challenge = challenge_for_date(date.today())
    payload: dict[str, Any] = {
        "date": challenge.date,
        "number": challenge.number,
        "rounds": challenge.rounds,
        "checkin_rounds": list(challenge.checkin_rounds),
        "min_bet": challenge.min_bet,
        "max_bet": challenge.max_bet,
        "bankroll": challenge.bankroll,
        "rules_summary": "Vegas Strip — 6 decks, S17, DAS, late surrender",
        "attempted": False,
        "result": None,
    }
    if profile_id:
        profile = await load_profile(profile_id)
        if profile and challenge.date in profile.daily:
            payload["attempted"] = True
            payload["result"] = profile.daily[challenge.date].model_dump(mode="json")
    return payload


@router.get("/badges")
async def list_badges() -> dict[str, Any]:
    """The badge book (definitions only; earned state lives on profiles)."""
    return {
        "badges": [
            {
                "id": b.id,
                "name": b.name,
                "flavor": b.flavor,
                "category": b.category,
                "secret": b.secret,
            }
            for b in BADGES.values()
        ]
    }
